--SELECT * FROM EMP_TABLE;
--SELECT * FROM DEP_TABLE;

--QUESTION: DISPLAY LIST OF DEPARTMENT WITH SUM OF EMPLOYEES SALARIES

/*SELECT DEP_NAME,SUM(SALARY)
FROM DEP_TABLE
 JOIN
EMP_TABLE
ON DEP_TABLE.DEP_ID = EMP_TABLE.DEP_ID
GROUP BY DEP_NAME;

*/

--QUESTION 2: LIST OF DEPT NAME ,SUM OF SALARY HAVING GREAT THAN 60000
/*SELECT DEP_NAME,SUM(SALARY)
FROM DEP_TABLE
 JOIN
EMP_TABLE
ON DEP_TABLE.DEP_ID = EMP_TABLE.DEP_ID
WHERE SALARY>60000
GROUP BY DEP_NAME;

*/

-- QUE 3: DISPLAY LIST FROM DEPT_NAME WHICH TOTAL EMPLOYEES GREATER THAN 1
/*SELECT DEP_NAME,COUNT(EMP_TABLE.DEP_ID) AS COUNT_
FROM DEP_TABLE
 JOIN
EMP_TABLE
ON DEP_TABLE.DEP_ID = EMP_TABLE.DEP_ID
GROUP BY DEP_NAME
HAVING COUNT(EMP_TABLE.DEP_ID)>1;

*/

--QUE 4: DISPLAY AVERAGE SALARY GREATER THAN 40000
SELECT DEP_NAME,AVG(SALARY) AS AVGERAGE
FROM DEP_TABLE
 JOIN
EMP_TABLE
ON DEP_TABLE.DEP_ID = EMP_TABLE.DEP_ID
GROUP BY DEP_NAME
HAVING AVG(SALARY)>60000

