declare @StartDate DATETIME, @EndDate DATETIME

SELECT @STARTDATE = '2021-11-01',@ENDDATE = '2021-12-01';
WITH LISTDATES(ALLDATES) AS
(    SELECT @STARTDATE AS DATETIME
     UNION ALL
	 SELECT DATEADD(DAY,1,ALLDATES)
	 --SELECT MONTH(MONTH,2,ALLDATES)
	 FROM LISTDATES
	 WHERE ALLDATES < @ENDDATE)

SELECT ALLDATES
FROM LISTDATES
 GO